version: '3.7'

services:
  frontend:
    container_name: frontend
    image: 361956036556.dkr.ecr.ap-south-1.amazonaws.com/dashboard-cil-prod:latest
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
